### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by wangz6uthscsa** [Khaliq12345/Obituary-scraper#1]
The API key seems expired. Where and how do you get it? Thanks!

**Comment by Khaliq12345** [comment]
> The API key seems expired. Where and how do you get it? Thanks!

Their website, I will see if I can get you the updated one.

**Comment by wangz6uthscsa** [comment]
Are you able to get the updated one? I didn't find it. Thanks!

**Comment by Khaliq12345** [comment]
You need to create account on scraper api: https://dashboard.scraperapi.com/
The api key will be on the dashboard

**Comment by wangz6uthscsa** [comment]
This is cool. Thank you! Also, how do you know about the legacy api? I mean this url: https://www.legacy.com/api/_frontend/localmarket/united-states/{state}/{c}?endDate={today_date}&limit=1000&offset=0&sortBy=date&startDate={start_date}. I used to use: https://www.legacy.com/obituaries/legacy/api/obituarysearch. It is not working any more.

**Comment by Khaliq12345** [comment]
I looked at their website's network traffic

**Comment by wangz6uthscsa** [comment]
Smart! Thank you!
